config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users, only: %i[create show]
  match 'signup' => 'users#new', :via => :get
  resources :events, only: %i[index show new create destroy]

  match 'send_invite' => 'users#send_invitation', :via => :post
  match 'accept_invite' => 'users#accept_invitation', :via => :post
  match 'decline_invite' => 'users#decline_invitation', :via => :post

  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :body, :location, :date, presence: true
  validates :name, :location, length: { maximum: 25 }
  validates :body, length: { minimum: 10 }

  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :invitations, dependent: :destroy
  has_many :pending_attendees, -> { where(invitations: { status: 0 }) }, class_name: 'User', through: :invitations, source: :user, dependent: :destroy
  has_many :attendees, -> { where(invitations: { status: 1 }) }, class_name: 'User', through: :invitations, source: :user, dependent: :destroy
  has_many :declined_attendees, -> { where(invitations: { status: 2 }) }, class_name: 'User', through: :invitations, source: :user, dependent: :destroy

  scope :past, -> { where('date < ?', DateTime.now) }
  scope :upcoming, -> { where('date > ?', DateTime.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  enum status: {
    'pending' => 0,
    'approved' => 1,
    'declined' => 2
  }
  belongs_to :user
  belongs_to :event

  validates_uniqueness_of :event_id, scope: [:user_id]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :events, foreign_key: :creator_id
  has_many :invitations
  has_many :pending_events, -> { where(invitations: { status: 0 }) }, class_name: 'Event', through: :invitations, source: :event
  has_many :attended_events, -> { where(invitations: { status: 1 }) }, class_name: 'Event', through: :invitations, source: :event
  has_many :declined_events, -> { where(invitations: { status: 2 }) }, class_name: 'Event', through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :require_logout, :require_signed_in

  def signed_in?
    session[:user_id]
  end

  def require_logout
    return unless signed_in?

    flash[:error] = 'You are already logged in'
    redirect_to root_url
  end

  def require_signed_in
    return if signed_in?

    flash[:error] = 'You must be logged in'
    redirect_to login_url
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_signed_in
  def index
    @past_events = Event.all.past
    @upcoming_events = Event.all.upcoming
  end

  def new
    @event = Event.new
  end

  def create
    user = User.find(session[:user_id])
    @event = Event.new(event_params)
    @event.creator = user
    if @event.save
      flash[:success] = 'Event created successfully'
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.where.not(id: session[:user_id])
  end

  def destroy
    event = Event.find(params[:id])
    if event.destroy!
      flash[:success] = 'Event successfully deleted'
      redirect_to root_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to event_url(event.id)
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :body, :location, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logout, only: [:new]
  def new; end

  def create
    user = User.find_by(name: params[:name])
    if user
      session[:user_id] = user.id
      flash[:success] = 'Logged in'
      redirect_to user_url(user.id)
    else
      flash.now[:error] = 'Invalid name'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logged out'
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logout, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:success] = "#{@user.name} has been created successfully"
        format.html { redirect_to login_url }
      else
        format.html { render :new }
      end
    end
  end

  def show
    respond_to do |format|
      if signed_in? && User.find_by_id(session[:user_id])
        @user = User.find_by_id(session[:user_id])
        @hosted_events = @user.events.upcoming
        @past_events = @user.attended_events.past
        @upcoming_events = @user.attended_events.upcoming
        format.html { @user }
      else
        flash[:alert] = 'You must be signed in'
        format.html { redirect_to login_url }
      end
    end
  end

  def send_invitation
    user = User.find(params[:user])
    event = Event.find(params[:event])
    begin
      user.pending_events << event
    rescue StandardError
      flash[:error] = 'Can not send invitation to this user'
      redirect_to event
    else
      flash[:success] = 'Invite sent sucessfully'
      redirect_to event
    end
  end

  def accept_invitation
    user = User.find(params[:user])
    event = Event.find(params[:event])
    invite = Invitation.find_by(user_id: user.id, event_id: event.id)
    invite.status = 1
    if invite.save
      flash[:success] = 'Invite accepted'
      redirect_to root_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to root_url
    end
  end

  def decline_invitation
    user = User.find(params[:user])
    user = User.find(params[:user])
    event = Event.find(params[:event])
    invite = Invitation.find_by(user_id: user.id, event_id: event.id)
    invite.status = 2
    if invite.save
      flash[:success] = 'Invite declined'
      redirect_to root_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to root_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    session[:user_id]
  end

  def signed_in_user_path
    user = User.find(session[:user_id])
    link_to(user.name, user_path(user.id))
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def users_available_to_invite
    invited_users = @event.pending_attendees
    declined_users = @event.declined_attendees
    attendees = @event.attendees
    users = User.all
    users.filter_map do |user|
      unless invited_users.include?(user) ||
             declined_users.include?(user) ||
             attendees.include?(user) ||
             @event.creator == user
        user
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_form.html.erb
<div class='section pt-1 pb-5'>
  <div class='columns is-centered'>
    <div class='column is-4'>
      <%= form_with(model: event, local: true) do |form| %>
        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %>
              prohibited this event from being saved:</h2>
            <ul>
              <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class='field'>
          <%= form.label :name, 'Event name:', class: 'label' %>
          <%= form.text_field :name, class: 'input' %>
        </div>
        <div class='field'>
          <%= form.label :body, 'Description:' , class: 'label'%>
          <%= form.text_area :body, size: "40x10", class: 'input' %>
        </div>
        <div class='field'>
          <%= form.label :location, 'Location:', class: 'label' %>
          <%= form.text_field :location, class: 'input' %>
        </div>
        <div class='field'>
          <%= form.label :date, 'Date:' , class: 'label'%>
          <%= form.datetime_local_field :date, class: 'input' %>
        </div>
        <div class='has-text-centered'>
          <%= form.submit 'Create Event', class: 'button is-medium' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_short_tb_display.html.erb
<td><%= link_to "#{event.name}", event %></td>
<td><%= event.creator.name %></td>
<td><%= event.date.localtime.to_formatted_s(:long) %></td>

app/views/events/index.html.erb
<h1 class='title is-4 has-text-centered'>All Events</h1>
<div class='columns is-multiline is-centered'>
  <div class='column is-1'></div>
  <div class='column is-10 has-text-centered'>
    <%= render 'users/upcoming_events' %>
  </div>
  <div class='column is-1'></div>
  <div class='column is-1'></div>
  <div class='column is-10 has-text-centered'>
    <%= render 'users/past_events' %>
  </div>
  <div class='column is-1'></div>
</div>

app/views/events/new.html.erb
<div class='level'>
  <h1 class='title is-4 level-item is-centered'>New Event</h1>
</div>
<br>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class='box has-text-centered'>
  <h1 class='title is-4 has-text-centered'><%= @event.name %></h1>
  <h3 class='subtitle has-text-centered'>Hosted by: <%= @event.creator.name %></h3>
  <p><%= @event.body %></p>
</div>
<div class='columns is-multiline has-text-centered'>
  <div class='column is-full'>
    <h3 class='subtitle'>Attendees:</h3>
    <% if @event.attendees.empty? %>
      <p>No attendees</p>
    <% else %>
      <table class='table is-bordered center'>
        <thead>
          <th>Name</th>
        </thead>
        <tbody>
          <% @event.attendees.each do |attendee| %>
            <tr>
              <td><%= attendee.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <br>
  </div>
  <div class='column is-4'>
    <% if session[:user_id] == @event.creator.id %>
      <h3 class='subtitle'>Send Invitations:</h3>
      <% if users_available_to_invite.empty? %>
        <p>No one is available</p>
      <% elsif @event.date < DateTime.now %>
        <p>Can not send invites</p>
      <% else %>
        <table class='table center'>
          <thead>
            <th>Name</th>
            <th>Invite</th>
          </thead>
          <tbody>
            <% users_available_to_invite.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td> <%= button_to 'Send Invite', send_invite_path, params: { user: user.id, event: @event.id }, class: 'button is-small is-info' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class='column is-4'>
      <h3 class='subtitle'>Pending Invitations:</h3>
      <% if @event.pending_attendees.empty? %>
        <p>No pending invitations</p>
      <% else %>
        <table class='table center'>
          <thead>
            <th>Name</th>
          </thead>
          <tbody>
            <% @event.pending_attendees.each do |user| %>
              <tr>
                <td><%= user.name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class='column is-4'>
      <h3 class='subtitle'>Declined Invitations:</h3>
      <% if @event.declined_attendees.empty? %>
        <p>No declined invitations</p>
      <% else %>
        <table class='table center'>
          <thead>
            <th>Name</th>
          </thead>
          <tbody>
            <% @event.declined_attendees.each do |user| %>
              <tr>
                <td><%= user.name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      <br>
      <br>
    </div>
    <div class='container has-text-centered'>
      <%= button_to 'Delete Event',  @event, method: :delete, data: {confirm: 'Are you sure?'}, class: 'button is-small is-danger' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class='navbar pb-6' role='navigation' aria-label='main navigation'>
      <div class='navbar-brand'>
        <%= link_to root_path, class: 'navbar-item' do %>
          <h1 class='title is-3 has-text-primary'>Private Events</h1>
        <% end %>
        <div role ='button' class='navbar-burger' data-target='navbarExample'>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id='navbarExample' class='navbar-menu'>
        <div class='navbar-end'>
          <% if signed_in? %>
            <p class='navbar-item'><%= signed_in_user_path %></p>
            <p class='navbar-item is-link'><%= link_to 'Logout', logout_path, method: :delete %></p>
          <% else %>
            <%= link_to signup_path, class: 'navbar-item' do %>
              <p>Sign Up</p>
            <% end %>
            <%= link_to login_path, class: 'navbar-item ' do %>
              <p>Login</p>
            <% end %>
          <% end %>
        </div>
      </div>
    </nav>
    <% if flash[:alert] %>
      <aside class='message is-warning' id='message'>
        <p class='message-header'>Notice</p>
        <p class='message-body'><%= flash[:alert] %></p>
      </aside>
    <% end %>
    <% if flash[:error]%>
      <aside class='message is-danger' id='message'>
        <p class='message-header'>Error</p>
        <p class='message-body'><%= flash[:error]%></p>
      </aside>
    <% end %>
    <% if flash[:success]%>
      <aside class='message is-success' id='message'>
        <p class='message-header'>Success</p>
        <p class='message-body'><%= flash[:success]%></p>
      </aside>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_declined_invites.html.erb
<div class='box'>
  <h3 class='subtitle'>Declined invites</h3>
  <% if @user.declined_events.empty? %>
    <p>You have no declined invites</p>
  <% else %>
    <table class='table is-fullwidth'>
      <thead>
        <th>Event name</th>
        <th>Host</th>
        <th>Date</th>
      </thead>
      <tbody >
        <% @user.declined_events.each do |event|%>
          <tr>
            <%= render 'events/short_tb_display', event: event %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class='columns is-centered'>
  <div class='column is-4'>
    <%= form_with(model: user, local: true) do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %>
            prohibited this user from being saved:</h2>
          <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class='field'>
        <%= form.label :name, class: 'label' %>
        <%= form.text_field :name, class: 'input' %>
      </div>
      <div class='has-text-centered'>
        <%= form.submit 'Sign Up', class: 'button is-medium' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_hosting_events.html.erb
<div class='box'>
  <h3 class='subtitle'>Events you are hosting:</h3>
  <% if @hosted_events.empty? %>
    <p>You are not hosting any events</p>
  <% else %>
    <table class='table is-fullwidth'>
      <thead>
        <th>Event name</th>
        <th>Date</th>
      </thead>
      <tbody >
        <% @hosted_events.each do |event|%>
          <tr>
            <td><%= link_to "#{event.name}", event %></td>
            <td><%= event.date.localtime.to_formatted_s(:long) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/_past_events.html.erb
<div class='box'>
  <h3 class='subtitle'>Past events:</h3>
  <% if @past_events.empty? %>
    <p>You have no past events</p>
  <% else %>
    <table class='table is-fullwidth'>
      <thead>
        <th>Event name</th>
        <th>Host</th>
        <th>Date</th>
      </thead>
      <tbody >
        <% @past_events.each do |event| %>
          <tr>
            <%= render 'events/short_tb_display', event: event %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/_pending_invites.html.erb
<div class='box'>
  <h3 class='subtitle'>Pending invites</h3>
  <% if @user.pending_events.empty? %>
    <p>You have no pending invites</p>
  <% else %>
    <table class='table is-fullwidth'>
      <thead>
        <th>Event name</th>
        <th>Host</th>
        <th>Date</th>
        <th>Accept</th>
        <th>Decline</th>
      </thead>
      <tbody >
        <% @user.pending_events.each do |event|%>
          <tr>
            <%= render 'events/short_tb_display', event: event %>
            <td><%= button_to 'Accept', accept_invite_path, params: { user: @user.id, event: event.id }, class: 'button is-small level-item mx-1 is-success' %></td>
            <td><%= button_to 'Decline', decline_invite_path, params: { user: @user.id, event: event.id }, class:'button is-small level-item mx-1 is-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/_upcoming_events.html.erb
<div class='box'>
  <h3 class='subtitle'>Upcoming events:</h3>
  <% if @upcoming_events.empty? %>
    <p>You have no events</p>
  <% else %>
    <table class='table is-fullwidth'>
      <thead>
        <th>Event name</th>
        <th>Host</th>
        <th>Date</th>
      </thead>
      <tbody >
        <% @upcoming_events.each do |event| %>
          <tr>
            <%= render 'events/short_tb_display', event: event %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class='title is-4 has-text-centered'>Sign Up</h1>
<%= render 'form', user: @user %>
<div class='has-text-centered'>
  <p>Already have an account? <%= link_to 'Login here', login_path %></p>
</div>

app/views/users/show.html.erb
<div class='columns is-multiline is-centered'>
  <div class='column is-full'>
    <h1 class='title is-4 has-text-centered'>Welcome <%= @user.name %>!</h1>
  </div>
  <div class='column is-one-quarter'></div>
  <div class='column is-half has-text-centered'>
    <%= render 'hosting_events'  %>
  </div>
  <div class='column is-one-quarter'></div>
  <div class='column is-full has-text-centered'>
    <%= button_to 'Create Event', new_event_path, method: :get, class: 'button is-medium' %>
  </div>
  <div class='column is-5 has-text-centered'>
    <%= render 'upcoming_events' %>
  </div>
  <div class='column is-1'></div>
  <div class='column is-5  has-text-centered'>
    <%= render 'past_events' %>
  </div>
  <div class='column is-full has-text-centered'>
    <%= button_to 'All Events',  events_path, method: :get, class: 'button is-medium' %>
  </div>
  <div class='column is-5 has-text-centered'>
    <%= render 'pending_invites' %>
  </div>
  <div class='column is-1'></div>
  <div class='column is-5  has-text-centered'>
    <%= render 'declined_invites' %>
  </div>
</div>